name: using actions yaml
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: build on ubuntu-latest
        uses: actions/checkout@v2
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
